### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by vetshopdeveloper** [quickshiftin/mage2-ordered-assets#10] opened 2018-12-14 06:44 UTC
[InvalidArgumentException]
  Plugin class Quickshiftin\Assetorderer\Config\Dom\UrnResolver doesn't exist

magento 2.2.7

**Comment by quickshiftin** [comment] 2018-12-14 13:08
Sorry for the issue, but thanks for the report!

Looks like I had 2 copies of `UrnResolver.php` in my dev site, so by removing the install and re-compiling I was able to reproduce this.

I've moved the `UrnResolver.php` to the correct folder now and pushed a new release (`1.1.1`). Please update and let me know if resolved for you.

**Comment by vetshopdeveloper** [comment] 2018-12-18 07:21
Installs fine but get the following now

1 exception(s):
Exception #0 (Exception): Notice: Undefined property: Quickshiftin\Assetorderer\View\Asset\Remote::$_oRealFile in /var/www/site.com.au/vendor/quickshiftin/assetorderer/View/Asset/Remote.php on line 30

Exception #0 (Exception): Notice: Undefined property: Quickshiftin\Assetorderer\View\Asset\Remote::$_oRealFile in /var/www/site.com.au/vendor/quickshiftin/assetorderer/View/Asset/Remote.php on line 30
#0 /var/www/site.com.au/vendor/quickshiftin/assetorderer/View/Asset/Remote.php(30): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined prope...', '/var/www/site...', 30, Array)
#1 /var/www/site.com.au/vendor/magento/framework/View/Page/Config/Renderer.php(392): Quickshiftin\Assetorderer\View\Asset\Remote->getContentType()
#2 /var/www/site.com.au/vendor/quickshiftin/assetorderer/View/Page/Config/Renderer.php(48): Magento\Framework\View\Page\Config\Renderer->getAssetContentType(Object(Quickshiftin\Assetorderer\View\Asset\Remote))
#3 /var/www/site.com.au/vendor/magento/framework/View/Page/Config/Renderer.php(261): Quickshiftin\Assetorderer\View\Page\Config\Renderer->renderAssetHtml(Object(Magento\Framework\View\Asset\PropertyGroup\Interceptor))
#4 /var/www/site.com.au/vendor/quickshiftin/assetorderer/View/Page/Config/Renderer.php(28): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(Object(Magento\Framework\View\Asset\PropertyGroup\Interceptor))
#5 /var/www/site.com.au/vendor/magento/framework/View/Page/Config/Renderer.php(101): Quickshiftin\Assetorderer\View\Page\Config\Renderer->renderAssets(Array)
#6 /var/www/site.com.au/vendor/magento/framework/View/Result/Page.php(249): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#7 /var/www/site.com.au/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /var/www/site.com.au/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#9 /var/www/site.com.au/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#10 /var/www/site.com.au/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#11 /var/www/site.com.au/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(26): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#12 /var/www/site.com.au/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#13 /var/www/site.com.au/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#14 /var/www/site.com.au/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#15 {mai

**Comment by quickshiftin** [comment] 2018-12-18 14:35
Interesting, it looks like you're using _remote_ assets. I don't have any of these in my project, thus have not tested this file. The good news is, it looks like it was just [a bogus identifier in Remote.php](https://github.com/quickshiftin/mage2-ordered-assets/commit/7c404e9d2f1779e55200fa039d532feddbf411b1#diff-2e790bd4c3a4bce1f8579c9910451166)

Please give it another shot. The latest version is 1.1.2.

**Comment by santibm** [comment] 2019-03-15 13:19
Hi! 

Just installed it through composer and got the same error:                                              
[InvalidArgumentException]                                                   
Plugin class Quickshiftin\Assetorderer\Config\Dom\UrnResolver doesn't exist  

Is fixed by moving the file to the right place, but just to let you know that the composer install is actually failing!

**Comment by quickshiftin** [comment] 2019-03-15 14:12
Hi @santibm , thanks for report (and sorry for issue)! I forgot to update `composer.json` with the latest tag, so the recent update was not in composer. I've just updated package.json and verified version `1.1.3` is out [on Packagitst](https://packagist.org/packages/quickshiftin/assetorderer). Please try again voa composer when you have a chance.

**Comment by santibm** [comment] 2019-03-15 14:30
Hi @quickshiftin, yeah composer require installs 1.1.3 now. Also the module does what I expected! Thanks for your work man!

**Comment by quickshiftin** [comment] 2019-03-15 14:33
@santibm Awesome news, thank you! If you could star the project I would greatly appreciate it!

**Closed as completed by quickshiftin** 2019-03-15 14:33 UTC
